title: John Ciolfi

# Site settings
description: "About John Ciolfi"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User settings
username: John Ciolfi
user_description: Hi, I'm John. I attended Northeastern University to get a BS in Computer Science & Mathematics, and I have continued my studies at Northeastern University to pursue a MS in Computer Science. Some areas of focus include backend API development, privacy & security, and computer networks.
user_title: Software Engineer
email: ciolfi.j [at] northeastern.edu

# https://pages.github.com/themes/
remote_theme: jciolfi/particle-jciolfi # jciolfi/minimal-jciolfi
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one